// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Models;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(BackendContext))]
    partial class BackendContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Cars.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MainPhotoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MainPhotoId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("backend.Models.Cars.CarSize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HeightId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LengthId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WeightId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WidthId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CarId")
                        .IsUnique();

                    b.HasIndex("HeightId");

                    b.HasIndex("LengthId");

                    b.HasIndex("WeightId");

                    b.HasIndex("WidthId");

                    b.ToTable("CarSizes");
                });

            modelBuilder.Entity("backend.Models.Cars.OfficialName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<string>("WikiLink")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarId")
                        .IsUnique();

                    b.HasIndex("SeriesId");

                    b.ToTable("OfficialNames");
                });

            modelBuilder.Entity("backend.Models.Cars.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstLevelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondLevelName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("backend.Models.Hardware.BoardEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Broken")
                        .HasColumnType("boolean");

                    b.Property<long>("PicoLocalTimestamp")
                        .HasColumnType("bigint");

                    b.Property<long>("ReceivedTimestamp")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("BoardEvents");
                });

            modelBuilder.Entity("backend.Models.Hardware.BreakBeamSensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Pin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("BreakBeamSensors");
                });

            modelBuilder.Entity("backend.Models.Hardware.PicoBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<bool>("Connected")
                        .HasColumnType("boolean");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PicoBoards");
                });

            modelBuilder.Entity("backend.Models.Hardware.SyncBoardResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("ClockAdjustedPicoTimestamp")
                        .HasColumnType("bigint");

                    b.Property<long?>("CurrentSyncOffset")
                        .HasColumnType("bigint");

                    b.Property<float?>("LastTenOffsetsAvg")
                        .HasColumnType("real");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<long?>("NewClockOffset")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PicoBoardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SyncFinishedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SyncResult")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PicoBoardId");

                    b.ToTable("SyncBoardResults");
                });

            modelBuilder.Entity("backend.Models.Misc.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CarId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("File")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("backend.Models.Misc.UnitValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UnitValues");
                });

            modelBuilder.Entity("backend.Models.Owners.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Circuits.Checkpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BreakBeamSensorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CircuitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BreakBeamSensorId");

                    b.HasIndex("CircuitId");

                    b.ToTable("Checkpoints");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Circuits.Circuit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Circuits");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Rounds.Races.Heats.HeatResults.RaceHeatSectorResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("AdvantagePoints")
                        .HasColumnType("real");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<float>("PositionPoints")
                        .HasColumnType("real");

                    b.Property<Guid>("RaceHeatResultId")
                        .HasColumnType("uuid");

                    b.Property<float>("Time")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("RaceHeatResultId");

                    b.ToTable("RaceHeatSectorResults");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Rounds.Races.Heats.HeatResults.SeasonEventRoundRaceHeatResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bonuses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("DistancePoints")
                        .HasColumnType("real");

                    b.Property<Guid>("HeatId")
                        .HasColumnType("uuid");

                    b.Property<float>("PointsSummed")
                        .HasColumnType("real");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("SeasonEventRoundRaceHeatResults");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SeasonEventRoundRaceHeatResult");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Rounds.Races.Heats.SeasonEventRoundRaceHeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("SeasonEventRoundRaceHeats");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Rounds.Races.SeasonEventRoundRace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("InstantAdvancements")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipantsCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<int>("SecondChances")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("SeasonEventRoundRaces");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Rounds.Races.SeasonEventRoundRaceResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid");

                    b.Property<float>("Points")
                        .HasColumnType("real");

                    b.Property<int?>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("RaceOutcome")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeasonEventRoundRaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("SeasonEventRoundRaceId");

                    b.ToTable("SeasonEventRoundRaceResults");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Rounds.SeasonEventRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DroppedCarsPointsStrategy")
                        .HasColumnType("integer");

                    b.Property<int>("DroppedCarsPositionDefinementStrategy")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipantsCount")
                        .HasColumnType("integer");

                    b.Property<int>("PointsStrategy")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeasonEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SecondChanceRulesId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeasonEventId");

                    b.HasIndex("SecondChanceRulesId")
                        .IsUnique();

                    b.ToTable("SeasonEventRounds");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Rounds.SecondChanceRules", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdvancesCount")
                        .HasColumnType("integer");

                    b.Property<int>("PointsStrategy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SecondChanceRules");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.SeasonEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CircuitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ScoreRulesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CircuitId")
                        .IsUnique();

                    b.HasIndex("ScoreRulesId")
                        .IsUnique();

                    b.HasIndex("SeasonId");

                    b.ToTable("SeasonEvents");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.SeasonEventScoreRules", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvailableBonuses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("DistanceMultiplier")
                        .HasColumnType("real");

                    b.Property<bool>("TheMoreTheBetter")
                        .HasColumnType("boolean");

                    b.Property<float>("TimeMultiplier")
                        .HasColumnType("real");

                    b.Property<float>("UnfinishedSectorPenaltyPoints")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("SeasonEventScoreRules");
                });

            modelBuilder.Entity("backend.Models.Seasons.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("backend.Models.Seasons.SeasonCarStanding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid");

                    b.Property<int>("Place")
                        .HasColumnType("integer");

                    b.Property<double>("Points")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("SeasonId");

                    b.ToTable("SeasonCarStandings");
                });

            modelBuilder.Entity("backend.Models.Seasons.SeasonTeamStanding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Place")
                        .HasColumnType("integer");

                    b.Property<double>("Points")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId");

                    b.ToTable("SeasonTeamStandings");
                });

            modelBuilder.Entity("backend.Models.Teams.Pot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Hierarchy")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Pots");
                });

            modelBuilder.Entity("backend.Models.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("CarPot", b =>
                {
                    b.Property<Guid>("CarsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PotsId")
                        .HasColumnType("uuid");

                    b.HasKey("CarsId", "PotsId");

                    b.HasIndex("PotsId");

                    b.ToTable("CarPot");
                });

            modelBuilder.Entity("CarSeasonEvent", b =>
                {
                    b.Property<Guid>("ParticipantsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonEventsId")
                        .HasColumnType("uuid");

                    b.HasKey("ParticipantsId", "SeasonEventsId");

                    b.HasIndex("SeasonEventsId");

                    b.ToTable("CarSeasonEvent");
                });

            modelBuilder.Entity("CarSeasonEventRound", b =>
                {
                    b.Property<Guid>("ParticipantsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonEventRoundsId")
                        .HasColumnType("uuid");

                    b.HasKey("ParticipantsId", "SeasonEventRoundsId");

                    b.HasIndex("SeasonEventRoundsId");

                    b.ToTable("CarSeasonEventRound");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Rounds.Races.Heats.HeatResults.RaceHeatResult", b =>
                {
                    b.HasBaseType("backend.Models.Seasons.Events.Rounds.Races.Heats.HeatResults.SeasonEventRoundRaceHeatResult");

                    b.HasIndex("HeatId");

                    b.HasDiscriminator().HasValue("RaceHeatResult");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Rounds.Races.Heats.HeatResults.TimeTrialHeatResult", b =>
                {
                    b.HasBaseType("backend.Models.Seasons.Events.Rounds.Races.Heats.HeatResults.SeasonEventRoundRaceHeatResult");

                    b.Property<float>("FullTime")
                        .HasColumnType("real");

                    b.Property<string>("SectorTimes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("TimePoints")
                        .HasColumnType("real");

                    b.HasIndex("HeatId");

                    b.HasDiscriminator().HasValue("TimeTrialHeatResult");
                });

            modelBuilder.Entity("backend.Models.Cars.Car", b =>
                {
                    b.HasOne("backend.Models.Misc.Photo", "MainPhoto")
                        .WithMany()
                        .HasForeignKey("MainPhotoId");

                    b.HasOne("backend.Models.Owners.Owner", "Owner")
                        .WithMany("Cars")
                        .HasForeignKey("OwnerId");

                    b.Navigation("MainPhoto");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("backend.Models.Cars.CarSize", b =>
                {
                    b.HasOne("backend.Models.Cars.Car", "Car")
                        .WithOne("Size")
                        .HasForeignKey("backend.Models.Cars.CarSize", "CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Misc.UnitValue", "Height")
                        .WithMany()
                        .HasForeignKey("HeightId");

                    b.HasOne("backend.Models.Misc.UnitValue", "Length")
                        .WithMany()
                        .HasForeignKey("LengthId");

                    b.HasOne("backend.Models.Misc.UnitValue", "Weight")
                        .WithMany()
                        .HasForeignKey("WeightId");

                    b.HasOne("backend.Models.Misc.UnitValue", "Width")
                        .WithMany()
                        .HasForeignKey("WidthId");

                    b.Navigation("Car");

                    b.Navigation("Height");

                    b.Navigation("Length");

                    b.Navigation("Weight");

                    b.Navigation("Width");
                });

            modelBuilder.Entity("backend.Models.Cars.OfficialName", b =>
                {
                    b.HasOne("backend.Models.Cars.Car", "Car")
                        .WithOne("OfficialName")
                        .HasForeignKey("backend.Models.Cars.OfficialName", "CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Cars.Series", "Series")
                        .WithMany("OfficialNames")
                        .HasForeignKey("SeriesId");

                    b.Navigation("Car");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("backend.Models.Hardware.BoardEvent", b =>
                {
                    b.HasOne("backend.Models.Hardware.BreakBeamSensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("backend.Models.Hardware.BreakBeamSensor", b =>
                {
                    b.HasOne("backend.Models.Hardware.PicoBoard", "Board")
                        .WithMany("BreakBeamSensors")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("backend.Models.Hardware.SyncBoardResult", b =>
                {
                    b.HasOne("backend.Models.Hardware.PicoBoard", "PicoBoard")
                        .WithMany("SyncBoardResults")
                        .HasForeignKey("PicoBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PicoBoard");
                });

            modelBuilder.Entity("backend.Models.Misc.Photo", b =>
                {
                    b.HasOne("backend.Models.Cars.Car", null)
                        .WithMany("Photos")
                        .HasForeignKey("CarId");
                });

            modelBuilder.Entity("backend.Models.Owners.Owner", b =>
                {
                    b.HasOne("backend.Models.Misc.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Circuits.Checkpoint", b =>
                {
                    b.HasOne("backend.Models.Hardware.BreakBeamSensor", "BreakBeamSensor")
                        .WithMany()
                        .HasForeignKey("BreakBeamSensorId");

                    b.HasOne("backend.Models.Seasons.Events.Circuits.Circuit", "Circuit")
                        .WithMany("Checkpoints")
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BreakBeamSensor");

                    b.Navigation("Circuit");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Rounds.Races.Heats.HeatResults.RaceHeatSectorResult", b =>
                {
                    b.HasOne("backend.Models.Seasons.Events.Rounds.Races.Heats.HeatResults.RaceHeatResult", "RaceHeatResult")
                        .WithMany("SectorResults")
                        .HasForeignKey("RaceHeatResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RaceHeatResult");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Rounds.Races.Heats.HeatResults.SeasonEventRoundRaceHeatResult", b =>
                {
                    b.HasOne("backend.Models.Cars.Car", "Car")
                        .WithMany("HeatResults")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Rounds.Races.Heats.SeasonEventRoundRaceHeat", b =>
                {
                    b.HasOne("backend.Models.Seasons.Events.Rounds.Races.SeasonEventRoundRace", "Race")
                        .WithMany("Heats")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Rounds.Races.SeasonEventRoundRace", b =>
                {
                    b.HasOne("backend.Models.Seasons.Events.Rounds.SeasonEventRound", "Round")
                        .WithMany("Races")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Rounds.Races.SeasonEventRoundRaceResult", b =>
                {
                    b.HasOne("backend.Models.Cars.Car", "Car")
                        .WithMany("RaceResults")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Seasons.Events.Rounds.Races.SeasonEventRoundRace", "SeasonEventRoundRace")
                        .WithMany("Results")
                        .HasForeignKey("SeasonEventRoundRaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("SeasonEventRoundRace");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Rounds.SeasonEventRound", b =>
                {
                    b.HasOne("backend.Models.Seasons.Events.SeasonEvent", "SeasonEvent")
                        .WithMany("Rounds")
                        .HasForeignKey("SeasonEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Seasons.Events.Rounds.SecondChanceRules", "SecondChanceRules")
                        .WithOne("Round")
                        .HasForeignKey("backend.Models.Seasons.Events.Rounds.SeasonEventRound", "SecondChanceRulesId");

                    b.Navigation("SeasonEvent");

                    b.Navigation("SecondChanceRules");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.SeasonEvent", b =>
                {
                    b.HasOne("backend.Models.Seasons.Events.Circuits.Circuit", "Circuit")
                        .WithOne("SeasonEvent")
                        .HasForeignKey("backend.Models.Seasons.Events.SeasonEvent", "CircuitId");

                    b.HasOne("backend.Models.Seasons.Events.SeasonEventScoreRules", "ScoreRules")
                        .WithOne("SeasonEvent")
                        .HasForeignKey("backend.Models.Seasons.Events.SeasonEvent", "ScoreRulesId");

                    b.HasOne("backend.Models.Seasons.Season", "Season")
                        .WithMany("Events")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circuit");

                    b.Navigation("ScoreRules");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("backend.Models.Seasons.SeasonCarStanding", b =>
                {
                    b.HasOne("backend.Models.Cars.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Seasons.Season", "Season")
                        .WithMany("Standings")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("backend.Models.Seasons.SeasonTeamStanding", b =>
                {
                    b.HasOne("backend.Models.Seasons.Season", null)
                        .WithMany("TeamStandings")
                        .HasForeignKey("SeasonId");

                    b.HasOne("backend.Models.Teams.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("backend.Models.Teams.Pot", b =>
                {
                    b.HasOne("backend.Models.Teams.Team", "Team")
                        .WithMany("Pots")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("backend.Models.Teams.Team", b =>
                {
                    b.HasOne("backend.Models.Seasons.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("CarPot", b =>
                {
                    b.HasOne("backend.Models.Cars.Car", null)
                        .WithMany()
                        .HasForeignKey("CarsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Teams.Pot", null)
                        .WithMany()
                        .HasForeignKey("PotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarSeasonEvent", b =>
                {
                    b.HasOne("backend.Models.Cars.Car", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Seasons.Events.SeasonEvent", null)
                        .WithMany()
                        .HasForeignKey("SeasonEventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarSeasonEventRound", b =>
                {
                    b.HasOne("backend.Models.Cars.Car", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Seasons.Events.Rounds.SeasonEventRound", null)
                        .WithMany()
                        .HasForeignKey("SeasonEventRoundsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Rounds.Races.Heats.HeatResults.RaceHeatResult", b =>
                {
                    b.HasOne("backend.Models.Seasons.Events.Rounds.Races.Heats.SeasonEventRoundRaceHeat", "Heat")
                        .WithMany("Results")
                        .HasForeignKey("HeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heat");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Rounds.Races.Heats.HeatResults.TimeTrialHeatResult", b =>
                {
                    b.HasOne("backend.Models.Seasons.Events.Rounds.Races.Heats.SeasonEventRoundRaceHeat", "Heat")
                        .WithMany()
                        .HasForeignKey("HeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heat");
                });

            modelBuilder.Entity("backend.Models.Cars.Car", b =>
                {
                    b.Navigation("HeatResults");

                    b.Navigation("OfficialName");

                    b.Navigation("Photos");

                    b.Navigation("RaceResults");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("backend.Models.Cars.Series", b =>
                {
                    b.Navigation("OfficialNames");
                });

            modelBuilder.Entity("backend.Models.Hardware.PicoBoard", b =>
                {
                    b.Navigation("BreakBeamSensors");

                    b.Navigation("SyncBoardResults");
                });

            modelBuilder.Entity("backend.Models.Owners.Owner", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Circuits.Circuit", b =>
                {
                    b.Navigation("Checkpoints");

                    b.Navigation("SeasonEvent")
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Rounds.Races.Heats.SeasonEventRoundRaceHeat", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Rounds.Races.SeasonEventRoundRace", b =>
                {
                    b.Navigation("Heats");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Rounds.SeasonEventRound", b =>
                {
                    b.Navigation("Races");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Rounds.SecondChanceRules", b =>
                {
                    b.Navigation("Round")
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.SeasonEvent", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.SeasonEventScoreRules", b =>
                {
                    b.Navigation("SeasonEvent")
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Seasons.Season", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Standings");

                    b.Navigation("TeamStandings");
                });

            modelBuilder.Entity("backend.Models.Teams.Team", b =>
                {
                    b.Navigation("Pots");
                });

            modelBuilder.Entity("backend.Models.Seasons.Events.Rounds.Races.Heats.HeatResults.RaceHeatResult", b =>
                {
                    b.Navigation("SectorResults");
                });
#pragma warning restore 612, 618
        }
    }
}
