LIFT_DELAY_SECONDS = 2
RELEASE_DURATION_SECONDS = 3

MOTOR_PIN_1 = 11
MOTOR_PIN_2 = 7
MOTOR_PIN_SPEED = 3

BOTTOM_SENSOR_PIN = 22
UPPER_SENSOR_PIN = 15

OFF_STATE = "OFF_STATE"
PENDING_STATE = "PENDING_STATE"
STAY_DOWN_STATE = "STAY_DOWN_STATE"
STAY_MIDDLE_STATE = "STAY_MIDDLE_STATE"
STAY_UP_STATE = "STAY_UP_STATE"
TEST_GO_UP_STATE = "TEST_GO_UP_STATE"
GO_UP_STATE = "GO_UP_STATE"
TEST_GO_DOWN_STATE = "TEST_GO_DOWN_STATE"
GO_DOWN_STATE = "GO_DOWN_STATE"
ARMED_STATE = "ARMED_STATE"
WAITING_STATE = "WAITING_STATE"
CAR_DETECTED_STATE = "CAR_DETECTED_STATE"
RELEASE_STATE = "RELEASE_STATE"